### get report
GET https://driversync.stage.prettysolution.com/api/report?LastEvaluatedKey=1736696290904
Content-Type: application/json
Authorization: prettysolution

### get report by id
GET https://driversync.stage.prettysolution.com/api/report/1736697319190
Content-Type: application/json
Authorization: prettysolution

### put report
PUT https://driversync.stage.prettysolution.com/api/report?hello=world
Content-Type: application/json
Authorization: prettysolution

{"type":"default"}

### debug
PUT https://driversync.stage.prettysolution.com/api/report/debug?hello=world
Content-Type: application/json
Authorization: prettysolution

{"type":"default"}


