### get reports (paginated)
GET {{host}}/api/report?LastEvaluatedKey=1736696290904
Content-Type: application/json
Authorization: prettysolution

### get one report by id
GET {{host}}/api/report/1736696290904
Content-Type: application/json
Authorization: prettysolution

### create report
PUT {{host}}/api/report?hello=world
Content-Type: application/json
Authorization: prettysolution

{"type":"default"}

### patch report
PATCH {{host}}/api/report/1736697686488
Content-Type: application/json
Authorization: prettysolution

{"type":"custom"}

### debug put
PUT {{host}}/api/report/debug?hello=world
Content-Type: application/json
Authorization: prettysolution

{"type":"default"}


### delete report
DELETE {{host}}/api/report/1736697686488
Content-Type: application/json
Authorization: prettysolution
